### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by BearzRobotics** [SirCmpwn/TrueCraft#272] opened 2017-07-24 23:59 UTC
whole [crash report](https://pastebin.com/pw8HrhCE)

What Happens is when i go to launch the game the launcher closes then reopens after this is printed out to the terminal.

Unhandled Exception:
System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
  at System.Buffer.BlockCopy (System.Array src, System.Int32 srcOffset, System.Array dst, System.Int32 dstOffset, System.Int32 count) [0x00097] in <f8c41931233d4f228b992016514838fa>:0 
  at TrueCraft.Client.Handlers.ChunkHandlers.HandleChunkData (TrueCraft.API.Networking.IPacket _packet, TrueCraft.Client.MultiplayerClient client) [0x000a8] in <3dfb1c8562d44a55b14b75d16df28ace>:0 
  at TrueCraft.Client.MultiplayerClient.ProcessNetwork (System.Net.Sockets.SocketAsyncEventArgs e) [0x000e4] in <3dfb1c8562d44a55b14b75d16df28ace>:0 
  at TrueCraft.Client.MultiplayerClient.OperationCompleted (System.Object sender, System.Net.Sockets.SocketAsyncEventArgs e) [0x00027] in <3dfb1c8562d44a55b14b75d16df28ace>:0 
  at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted (System.Net.Sockets.SocketAsyncEventArgs e) [0x0000e] in <19c1c467abe1427e9b63f65c1fb1bfb0>:0 
  at System.Net.Sockets.SocketAsyncEventArgs.Complete () [0x00000] in <19c1c467abe1427e9b63f65c1fb1bfb0>:0 
  at System.Net.Sockets.Socket+<>c.<.cctor>b__306_7 (System.IAsyncResult ares) [0x0005d] in <19c1c467abe1427e9b63f65c1fb1bfb0>:0 
  at System.Net.Sockets.SocketAsyncResult+<>c__DisplayClass27_0.<Complete>b__0 (System.Object _) [0x00000] in <19c1c467abe1427e9b63f65c1fb1bfb0>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <f8c41931233d4f228b992016514838fa>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <f8c41931233d4f228b992016514838fa>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <f8c41931233d4f228b992016514838fa>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
  at System.Buffer.BlockCopy (System.Array src, System.Int32 srcOffset, System.Array dst, System.Int32 dstOffset, System.Int32 count) [0x00097] in <f8c41931233d4f228b992016514838fa>:0 
  at TrueCraft.Client.Handlers.ChunkHandlers.HandleChunkData (TrueCraft.API.Networking.IPacket _packet, TrueCraft.Client.MultiplayerClient client) [0x000a8] in <3dfb1c8562d44a55b14b75d16df28ace>:0 
  at TrueCraft.Client.MultiplayerClient.ProcessNetwork (System.Net.Sockets.SocketAsyncEventArgs e) [0x000e4] in <3dfb1c8562d44a55b14b75d16df28ace>:0 
  at TrueCraft.Client.MultiplayerClient.OperationCompleted (System.Object sender, System.Net.Sockets.SocketAsyncEventArgs e) [0x00027] in <3dfb1c8562d44a55b14b75d16df28ace>:0 
  at System.Net.Sockets.SocketAsyncEventArgs.OnCompleted (System.Net.Sockets.SocketAsyncEventArgs e) [0x0000e] in <19c1c467abe1427e9b63f65c1fb1bfb0>:0 
  at System.Net.Sockets.SocketAsyncEventArgs.Complete () [0x00000] in <19c1c467abe1427e9b63f65c1fb1bfb0>:0 
  at System.Net.Sockets.Socket+<>c.<.cctor>b__306_7 (System.IAsyncResult ares) [0x0005d] in <19c1c467abe1427e9b63f65c1fb1bfb0>:0 
  at System.Net.Sockets.SocketAsyncResult+<>c__DisplayClass27_0.<Complete>b__0 (System.Object _) [0x00000] in <19c1c467abe1427e9b63f65c1fb1bfb0>:0 
  at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem () [0x00008] in <f8c41931233d4f228b992016514838fa>:0 
  at System.Threading.ThreadPoolWorkQueue.Dispatch () [0x00074] in <f8c41931233d4f228b992016514838fa>:0 
  at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback () [0x00000] in <f8c41931233d4f228b992016514838fa>:0 
AL lib: (EE) alc_cleanup: 2 devices not closed

**Comment by lanodan** [comment] 2017-07-25 04:53
I think this is a duplicate of https://github.com/SirCmpwn/TrueCraft/issues/268

**Closed** 2017-07-25 13:00 UTC

**Comment by BearzRobotics** [comment] 2017-07-25 13:08
Thanks I'm going to close this issue because it is a duplicate o [268](https://github.com/SirCmpwn/TrueCraft/issues/268)
