### ISSUE TITLE
Migration to OpenTK

### ISSUE THREAD

**Issue by mrpimpunicorn** [SirCmpwn/TrueCraft#170] opened 2015-06-25 22:17 UTC
We should really move to a better cross-platform framework. I suggest OpenTK, since I've already written almost an entire layer of abstraction on-top of it and can just pull it all into a new project file. We can discuss migration details here.

**Comment by SirCmpwn** [comment] 2015-06-25 23:21
My understanding of the advantages of using OpenTK:

* One download for all platforms without stupid bullshit like we do now
* Shaders aren't stupid

Disadvantages:

* Reduce chances of iOS or Android port
* Lots of work to switch

Comments:

* An iOS/Android port would be pretty difficult anyway

Is this correct?

**Comment by mrpimpunicorn** [comment] 2015-06-25 23:28
Yeah, that's pretty much it.

**Comment by SirCmpwn** [comment] 2015-06-25 23:29
Alright, then let's do it. Did you want to lead this effort?

**Comment by mrpimpunicorn** [comment] 2015-06-25 23:35
I dunno; I could lead, but it would be nice if the endeavor was hosted in this repo, not one of my own. We should also decide what the result is going to be before jumping in. I doubt you want 5 thousand lines of OpenGL abstractions cluttering the client namespace; perhaps a ```TrueCraft.Client.Runtime``` project for 'engine' logic?

**Comment by SirCmpwn** [comment] 2015-06-25 23:37
I was going to suggest giving you write access to this repository to facilitate that.

As for abstractions, sure, `TrueCraft.Client.Runtime` sounds fine to me.

**Comment by mrpimpunicorn** [comment] 2015-06-25 23:42
Write access would make this a lot easier.

**Comment by SirCmpwn** [comment] 2015-06-25 23:44
Cool. I'll give you write access and we can get started. I'm a bit tied up tonight, but I'll help out starting tomorrow.

    We trust you have received the usual lecture from the local System
    Administrator. It usually boils down to these three things:
    #1) Respect the privacy of others.
    #2) Think before you type.
    #3) With great power comes great responsibility.

**Comment by SirCmpwn** [comment] 2015-06-25 23:44
Let's do this in a new `opentk` branch until we get things working at the degree they are now with MonoGame.

**Comment by mrpimpunicorn** [comment] 2015-06-25 23:45
Sounds good.

**Comment by Aragas** [comment] 2015-06-26 00:33
Why is monogame stuff stupid? There are obvious reasons for it, platforms are different. You are digging a hole, from which you can't later escape.

**Comment by SirCmpwn** [comment] 2015-06-26 00:34
See discussion here: https://github.com/SirCmpwn/TrueCraft/pull/169

**Comment by Aragas** [comment] 2015-06-26 00:36
That's a bit weird. Was there a problem with compiling and using shaders? I have written custom shaders and they work both on android and windows.

**Comment by SirCmpwn** [comment] 2015-06-26 00:37
We can't compile shaders *from* Linux. The ability to compile the code is dependent on your platform.

**Comment by SirCmpwn** [comment] 2015-06-26 00:37
Also, the majority of the work here is not in the client's rendering layer. That can easily be replaced. We are not committing ourselves to an inescapable fate.

**Comment by Aragas** [comment] 2015-06-26 00:40
The problem is with opengl es. There are differincies that would need to do stuff like #if ANDROID.

**Comment by SirCmpwn** [comment] 2015-06-26 00:41
I mentioned earlier that mobile is not an important target for TrueCraft.

**Comment by Aragas** [comment] 2015-06-26 00:43
Okay, then this topic is closed. OpenTK do have better performance compared to monogame

**Comment by mrpimpunicorn** [comment] 2015-06-26 00:44
Yeah, because MonoGame is just an XNA shim on top of OpenTK.

**Comment by mrpimpunicorn** [comment] 2015-06-26 01:08
I've pushed _most_ OpenGL wrapper code to ```opentk```, there are a few gotchas since this is all code I've written before and have just imported into this project;
- Declarations of inheritance and implementation are indented, feel free to run a macro replacing ```\n:``` with ``` :```, I'll probably do that anyways.
- Most types are disposable. This is due to the fact that OpenGL handles *need* to be deterministically disposed of. The pattern is any objects encapsulating handles inherit from ```SafeHandle```, which provides proper methods of disposal and the possibility of implementing an OpenGL handle 'finalizer' later on. Any objects containing ```SafeHandle``` or derived members should implement IDisposable, but needn't override their finalizer or raise disposal events.
- Enumerations and other value types are essentially their equivalent OpenTK value types. This is because the code was intended to be a complete game runtime; you shouldn't have to even know it's based on OpenTK to use it.
- Because the proper IDisposable pattern is throwing an ```ObjectDisposedException``` if an object is accessed in any way after disposal, I've implemented most properties literally, instead of letting the compiler auto-generate them.
- The Input namespace is essentially a thin shim around OpenTK. Again, the code was intended to be a complete runtime. Think of it as having the ability to extend/modify keyboard functionality later, without forking OpenTK and modifying ```KeyboardDevice```.
- Other miscellaneous style guide (violations?). We can probably fix those up with macros, like I said earlier.

That's all I can think of off the top of my head, I still have an OpenAL wrapper we can import when we get to that point, as well. If you have any questions or suggestions don't hesitate to ask.

**Comment by SirCmpwn** [comment] 2015-06-26 13:23
It looks good. I'd like to see how it's going to integrate with the client.

**Comment by mrpimpunicorn** [comment] 2015-06-26 13:27
Sure, should we purge the files in the client on this branch and port them over one-by-one from master, or just slowly rewrite all of them?

**Comment by SirCmpwn** [comment] 2015-06-26 13:28
I'm in favor of the "change the dependencies and fix build errors until it works" approach.

**Comment by SirCmpwn** [comment] 2015-06-26 13:28
Also, if we're providing our own `Vector{2,3,4}`, can we just use the TrueCraft.Core implementations?

**Comment by mrpimpunicorn** [comment] 2015-06-26 13:42
Yeah, probably. We'll have to make sure TrueCraft's vector structs have a ``[StructLayout(LayoutKind.Sequential)]``` attribute, and the field order is X, Y, Z, W.

**Comment by SirCmpwn** [comment] 2015-06-26 13:42
We do already have that, but we'll need to add a Vector4 class.

**Comment by mrpimpunicorn** [comment] 2015-06-26 14:27
Unfortunately TrueCraft's vector class uses double-precision components. We can't feed those to OpenGL without expecting a huge performance hit because graphics cards are optimized for single-precision.

**Comment by SirCmpwn** [comment] 2015-06-26 14:28
Ah. Well, I'd prefer to switch our vectors to single-precision over having two vector implementations floating around.

**Comment by SirCmpwn** [comment] 2015-06-26 14:29
Actually, that has some protocol implications that we can't really turn a blind eye to. For now I suppose we can just live with two implementations.

**Comment by mrpimpunicorn** [comment] 2015-06-26 16:34
There's an implementation of XNA's math library released under the MIT license [here](http://www.technologicalutopia.com/sourcecode/xnageometry/tableofcontents.htm), we should probably make use of these classes (especially ```BoundingFrustum```) to save ourselves from writing replicas.

**Comment by SirCmpwn** [comment] 2015-06-26 16:34
Sure.

**Comment by mrpimpunicorn** [comment] 2015-06-26 19:47
Do we want to encode shader information (type + source code) in a JSON file or an XML file?

**Comment by SirCmpwn** [comment] 2015-06-26 19:51
How about just source? Then we can annotate it like so:

    // Some shader v1.2.3.4
    // key=value
    // key=value
    // ...

    [ source code ]

**Comment by mrpimpunicorn** [comment] 2015-06-26 20:11
That works.

**Comment by SirCmpwn** [comment] 2015-06-27 13:49
I'm not entirely sure what's going on in the OpenTK branch right now. How can I help?

**Comment by mrpimpunicorn** [comment] 2015-06-27 14:50
It's a bit complicated. The ```Input``` namespace is complete, you might want to add key bindings after we reach our stage of development in XNA. The ```Maths``` namespace contains the  XnaGeometry library, so if you want an XNA math class like ```BoundingFrustum```, import it from there. The ```Graphics``` namespace is where most of the work is being done right now. There are the more abstract classes like sprite-rendering, meshes, and camera in the base namespace, with the ```OpenGL``` one containing specific, low-level classes. For the most part the ```OpenGL``` namespace is complete, with the exception of a ```Texture1D```, ```Texture3D```, and ```TextureCube``` classes. In the ```Graphics``` namespace we have sprite rendering which needs to be completed. I'm working on a content-caching system so that we can load our textures without using ```System.Drawing``` and load custom shader source files. Other than that, the entire TrueCraft client still needs to be ported to the runtime.

**Comment by StianTheDark** [comment] 2015-08-16 20:03
Progress report? Haven't seen activity in the branch in a while.

**Comment by SirCmpwn** [comment] 2015-08-16 20:11
Busy with other projects. Feel free to contribute more to get this one done faster.

**Comment by SirCmpwn** [comment] 2015-09-01 12:24
Sorry I've been busy. Returning my focus to TrueCraft and will be investigating this today.

**Comment by SirCmpwn** [comment] 2015-09-01 22:32
After banging my head on this for a while, I'm thinking that we might want to drop this effort and instead focus on getting MonoGame working consistently across platforms. The key issues with MonoGame are:

* Weirdness on Windows (solvable)
* Unable to compile shaders on non-Windows platforms (unsolvable)

The second one is a big problem. As for the first one, I don't use Windows and I'm unwilling to buy a Windows license. So, this merits some discussion. For now, I think that we can live with BasicEffect and wait for MonoGame to get their shit together. Anyone have thoughts?

**Comment by mrpimpunicorn** [comment] 2015-09-01 22:39
I don't have any complaints, as long as client development can resume. It's strange, however, that moving to OpenTK causes issues on Linux, since MonoGame uses it under the hood?

**Comment by SirCmpwn** [comment] 2015-09-01 22:40
MonoGame does use it under the hood, but it's pretty poorly documented and I'm having a hard time figuring out why the stripped down demo doesn't work, or even finding anyone else's stripped down demo to test with.

**Comment by mrpimpunicorn** [comment] 2015-09-01 22:55
Yeah, most OpenGL demos are in C/++, and OpenTK isn't a 100% faithful implementation of the OpenGL API anyways.

**Closed** 2015-09-28 02:59 UTC
