### ISSUE TITLE
Build instructions are too scarce

### ISSUE THREAD

**Issue by Calinou** [SirCmpwn/TrueCraft#42] opened 2015-05-01 12:38 UTC
I'm on Debian jessie 64-bit, installed xbuild from packages. I followed the instructions in the README, typed `xbuild` in the TrueCraft folder (cloned from Git recursively) and got:
```
XBuild Engine Version 12.0
Mono, Version 3.2.8.0
Copyright (C) 2005-2013 Various Mono authors

Build started 01/05/2015 14:36:00.
__________________________________________________
Project "/home/calinou/Git/truecraft/TrueCraft.sln" (default target(s)):
	Target ValidateSolutionConfiguration:
		Building solution configuration "Debug|x86".
	Target Build:
		Project "/home/calinou/Git/truecraft/externals/fNbt/fNbt/fNbt.csproj" (default target(s)):
			Target PrepareForBuild:
: error : Error initializing task Message: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.
			Task "Message" execution -- FAILED
			Done building target "PrepareForBuild" in project "/home/calinou/Git/truecraft/externals/fNbt/fNbt/fNbt.csproj".-- FAILED
			Target _RecordCleanFile:
: error : Error initializing task ReadLinesFromFile: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.
			Task "ReadLinesFromFile" execution -- FAILED
			Done building target "_RecordCleanFile" in project "/home/calinou/Git/truecraft/externals/fNbt/fNbt/fNbt.csproj".-- FAILED
		Done building project "/home/calinou/Git/truecraft/externals/fNbt/fNbt/fNbt.csproj".-- FAILED
	Task "MSBuild" execution -- FAILED
	Done building target "Build" in project "/home/calinou/Git/truecraft/TrueCraft.sln".-- FAILED
Done building project "/home/calinou/Git/truecraft/TrueCraft.sln".-- FAILED

Build FAILED.
Errors:

/home/calinou/Git/truecraft/TrueCraft.sln (default targets) ->
(Build target) ->
/home/calinou/Git/truecraft/externals/fNbt/fNbt/fNbt.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (PrepareForBuild target) ->

	: error : Error initializing task Message: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.

/home/calinou/Git/truecraft/TrueCraft.sln (default targets) ->
(Build target) ->
/home/calinou/Git/truecraft/externals/fNbt/fNbt/fNbt.csproj (default targets) ->
/usr/lib/mono/4.5/Microsoft.Common.targets (_RecordCleanFile target) ->

	: error : Error initializing task ReadLinesFromFile: Could not load file or assembly 'Microsoft.Build.Tasks.v4.0' or one of its dependencies. The system cannot find the file specified.

	 0 Warning(s)
	 2 Error(s)

Time Elapsed 00:00:00.1781310
```

What do I need to do for it to build? I've never built a C# program before, so I have no idea what to do.

Also, does TrueCraft require game data from Minecraft? You should probably mention it in the README; if it does, I can work on getting replacement data for those who don't have Minecraft.

**Comment by SirCmpwn** [comment] 2015-05-01 12:56
Duplicate of #41.

>Also, does TrueCraft require game data from Minecraft? You should probably mention it in the README; if it does, I can work on getting replacement data for those who don't have Minecraft.

No, it does not require anything from Minecraft.

**Closed by SirCmpwn** 2015-05-01 12:56 UTC

**Comment by cyisfor** [comment] 2015-09-17 23:10
Not a duplicate, because fnBt is a git submodule unlike the other uh... things?

git submodule update was what fixed it for me. The 'git clone' by itself didn't checkout the fnBt submodule.

...maybe also git submodule init?
