### ISSUE TITLE
Fullscreen still doesn't work on Windows

### ISSUE THREAD

**Issue by ShaunNoWay** [SirCmpwn/TrueCraft#207] opened 2015-10-01 19:34 UTC
MrPimpUnicorn posted a couple months back [(issue #132)](https://github.com/SirCmpwn/TrueCraft/issues/132) that MonoGame's fullscreen function doesn't work on Windows 7 64-bit. I just wanted to confirm that fullscreen doesn't work on my Windows machine either (Windows 10, 64-bit) and bring some attention to it in hopes of a fix.

**Comment by SirCmpwn** [comment] 2015-10-01 19:34
...dupe of #132

**Closed by SirCmpwn** 2015-10-01 19:34 UTC

**Comment by ShaunNoWay** [comment] 2015-10-01 19:38
Crap, sorry. I probably should've just replied to that issue thread instead of just reiterating it. Sorry for my lack of Git-iquette
