### ISSUE TITLE
where is the fNbt.csproj?

### ISSUE THREAD

**Issue by lantianning** [SirCmpwn/TrueCraft#213] opened 2015-10-10 13:14 UTC
I have been read the redme..
https://github.com/SirCmpwn/TrueCraft#compiling

I press your suggestion to do still error.
where is the fNbt.csproj?

**Comment by SirCmpwn** [comment] 2015-10-10 13:15
Duplicate of #175. You didn't restore nuget packages, and you didn't actually read it.

**Closed by SirCmpwn** 2015-10-10 13:15 UTC

**Comment by lantianning** [comment] 2015-10-10 13:28
i has been restore nuget packages.i use vs 2012 and nuget.exe

**Comment by SirCmpwn** [comment] 2015-10-10 13:29
Sorry, it's not nuget packages, it's the git submodules. You did not read the instructions.

**Comment by lantianning** [comment] 2015-10-10 13:39
oh sorry , i try again.

**Comment by lantianning** [comment] 2015-10-11 01:09
it work.thank you.
