### ISSUE TITLE
I can not break any block or place anything

### ISSUE THREAD

**Issue by Pollito001** [SirCmpwn/TrueCraft#248] opened 2016-05-03 18:15 UTC
I run the game but i can not break any block or place anything and no sky in the last version on linux, any help to make the game looks like the one in the website pictures?
My Specs:
Distro: Manjaro Linux
Kernel: 4.4.8-1-MANJARO x86_64 
Desktop: Xfce 4.12.3 (Gtk 2.24.28) 
CPU: Dual core AMD E-300 APU with Radeon HD Graphics
GPU: Card: Advanced Micro Devices [AMD/ATI] Wrestler [Radeon HD 6310] - Driver Gallium

**Comment by MggMuggins** [comment] 2017-04-24 18:42
I've experienced this as well. However, a restart of the game fixed it for me. Press escape and launch again.

**Comment by SirCmpwn** [comment] 2017-05-23 22:42
Cannot reproduce, closing due to lack of information

**Closed by SirCmpwn** 2017-05-23 22:42 UTC
